const routes = [
  [
    { name: 'Home', route: '/', icon: 'home' },
    { name: 'Contact', route: '/contact', icon: 'contact' },
    { name: 'About', route: '/about', icon: 'about' },
  ],
  [
    { name: 'Chapters', route: '/chapters', icon: 'chapters' },
    { name: 'Grades', route: '/grades', icon: 'chapters' },
  ],
  [
    { name: 'Theme 1', route: '/chapters/1/theme/1', icon: 'theme' },
    { name: 'Theme 2', route: '/chapters/1/theme/2', icon: 'theme' },
    { name: 'Theme 3', route: '/chapters/1/theme/3', icon: 'theme' },
    { name: 'Theme 4', route: '/chapters/1/theme/4', icon: 'theme' },
  ],
  [
    { name: 'Theme 1', route: '/chapters/2/theme/1', icon: 'theme' },
    { name: 'Theme 2', route: '/chapters/2/theme/2', icon: 'theme' },
    { name: 'Theme 3', route: '/chapters/2/theme/3', icon: 'theme' },
    { name: 'Theme 4', route: '/chapters/2/theme/4', icon: 'theme' },
    { name: 'Theme 5', route: '/chapters/2/theme/5', icon: 'theme' },
  ],
  [
    { name: 'Theme 1', route: '/chapters/3/theme/1', icon: 'theme' },
    { name: 'Theme 2', route: '/chapters/3/theme/2', icon: 'theme' },
    { name: 'Theme 3', route: '/chapters/3/theme/3', icon: 'theme' },
    { name: 'Theme 4', route: '/chapters/3/theme/4', icon: 'theme' },
    { name: 'Theme 5', route: '/chapters/3/theme/5', icon: 'theme' },
  ],
  [
    { name: 'Theme 1', route: '/chapters/4/theme/1', icon: 'theme' },
    { name: 'Theme 2', route: '/chapters/4/theme/2', icon: 'theme' },
    { name: 'Theme 3', route: '/chapters/4/theme/3', icon: 'theme' },
    { name: 'Theme 4', route: '/chapters/4/theme/4', icon: 'theme' },
  ],
  [
    { name: 'Theme 1', route: '/chapters/5/theme/1', icon: 'theme' },
    { name: 'Theme 2', route: '/chapters/5/theme/2', icon: 'theme' },
  ],
  [
    { name: 'Theme 1', route: '/chapters/6/theme/1', icon: 'theme' },
    { name: 'Theme 2', route: '/chapters/6/theme/1', icon: 'theme' },
    { name: 'Theme 3', route: '/chapters/6/theme/1', icon: 'theme' },
    { name: 'Theme 4', route: '/chapters/6/theme/1', icon: 'theme' },
    { name: 'Theme 5', route: '/chapters/6/theme/1', icon: 'theme' },
    { name: 'Theme 6', route: '/chapters/6/theme/2', icon: 'theme' },
    { name: 'Theme 7', route: '/chapters/6/theme/2', icon: 'theme' },
    { name: 'Theme 8', route: '/chapters/6/theme/2', icon: 'theme' },
    { name: 'Theme 9', route: '/chapters/6/theme/2', icon: 'theme' },
    { name: 'Theme 10', route: '/chapters/6/theme/2', icon: 'theme' },
    { name: 'Theme 11', route: '/chapters/6/theme/2', icon: 'theme' },
    { name: 'Theme 12', route: '/chapters/6/theme/2', icon: 'theme' },
  ],
  [
    { name: 'Theme 1', route: '/chapters/7/theme/1', icon: 'theme' },
    { name: 'Theme 2', route: '/chapters/7/theme/1', icon: 'theme' },
    { name: 'Theme 3', route: '/chapters/7/theme/1', icon: 'theme' },
    { name: 'Theme 4', route: '/chapters/7/theme/1', icon: 'theme' },
    { name: 'Theme 5', route: '/chapters/7/theme/1', icon: 'theme' },
    { name: 'Theme 6', route: '/chapters/7/theme/2', icon: 'theme' },
    { name: 'Theme 7', route: '/chapters/7/theme/2', icon: 'theme' },
    { name: 'Theme 8', route: '/chapters/7/theme/2', icon: 'theme' },
    { name: 'Theme 9', route: '/chapters/7/theme/2', icon: 'theme' },
    { name: 'Theme 10', route: '/chapters/7/theme/2', icon: 'theme' },
  ],
  [
    { name: 'Theme 1', route: '/chapters/8/theme/1', icon: 'theme' },
    { name: 'Theme 2', route: '/chapters/8/theme/1', icon: 'theme' },
    { name: 'Theme 3', route: '/chapters/8/theme/1', icon: 'theme' },
  ],
  [
    { name: 'Theme 1', route: '/chapters/9/theme/1', icon: 'theme' },
    { name: 'Theme 2', route: '/chapters/9/theme/1', icon: 'theme' },
    { name: 'Theme 3', route: '/chapters/9/theme/1', icon: 'theme' },
    { name: 'Theme 4', route: '/chapters/9/theme/1', icon: 'theme' },
    { name: 'Theme 5', route: '/chapters/9/theme/1', icon: 'theme' },
  ],
  [
    { name: 'grade theme 1', route: '/grades/1/theme/1', icon: 'theme' },
    { name: 'grade theme 2', route: '/grades/1/theme/1', icon: 'theme' },
    { name: 'grade theme 3', route: '/grades/1/theme/1', icon: 'theme' },
    { name: 'grade theme 4', route: '/grades/1/theme/1', icon: 'theme' },
    { name: 'grade theme 5', route: '/grades/1/theme/1', icon: 'theme' },
  ],
  [
    { name: 'grade theme 1', route: '/grades/2/theme/1', icon: 'theme' },
    { name: 'grade theme 2', route: '/grades/2/theme/2', icon: 'theme' },
    { name: 'grade theme 3', route: '/grades/2/theme/3', icon: 'theme' },
    { name: 'grade theme 4', route: '/grades/2/theme/4', icon: 'theme' },
    { name: 'grade theme 5', route: '/grades/2/theme/5', icon: 'theme' },
    { name: 'grade theme 6', route: '/grades/2/theme/6', icon: 'theme' },
    { name: 'grade theme 7', route: '/grades/2/theme/7', icon: 'theme' },
    { name: 'grade theme 8', route: '/grades/2/theme/8', icon: 'theme' },
    { name: 'grade theme 9', route: '/grades/2/theme/9', icon: 'theme' },
    { name: 'grade theme 10', route: '/grades/2/theme/10', icon: 'theme' },
    { name: 'grade theme 11', route: '/grades/2/theme/11', icon: 'theme' },
    { name: 'grade theme 12', route: '/grades/2/theme/12', icon: 'theme' },
    { name: 'grade theme 13', route: '/grades/2/theme/13', icon: 'theme' },
    { name: 'grade theme 14', route: '/grades/2/theme/14', icon: 'theme' },
    { name: 'grade theme 15', route: '/grades/2/theme/15', icon: 'theme' },
    { name: 'grade theme 16', route: '/grades/2/theme/16', icon: 'theme' },
    { name: 'grade theme 17', route: '/grades/2/theme/17', icon: 'theme' },
    { name: 'grade theme 18', route: '/grades/2/theme/18', icon: 'theme' },
  ],
  [
    { name: 'grade theme 1', route: '/grades/3/theme/1', icon: 'theme' },
    { name: 'grade theme 2', route: '/grades/3/theme/2', icon: 'theme' },
    { name: 'grade theme 3', route: '/grades/3/theme/3', icon: 'theme' },
    { name: 'grade theme 4', route: '/grades/3/theme/4', icon: 'theme' },
    { name: 'grade theme 5', route: '/grades/3/theme/5', icon: 'theme' },
    { name: 'grade theme 6', route: '/grades/3/theme/6', icon: 'theme' },
    { name: 'grade theme 7', route: '/grades/3/theme/7', icon: 'theme' },
    { name: 'grade theme 8', route: '/grades/3/theme/8', icon: 'theme' },
    { name: 'grade theme 9', route: '/grades/3/theme/9', icon: 'theme' },
    { name: 'grade theme 10', route: '/grades/3/theme/10', icon: 'theme' },
  ],
  [
    { name: 'grade theme 1', route: '/grades/4/theme/1', icon: 'theme' },
    { name: 'grade theme 2', route: '/grades/4/theme/2', icon: 'theme' },
    { name: 'grade theme 3', route: '/grades/4/theme/3', icon: 'theme' },
    { name: 'grade theme 4', route: '/grades/4/theme/4', icon: 'theme' },
    { name: 'grade theme 5', route: '/grades/4/theme/5', icon: 'theme' },
    { name: 'grade theme 6', route: '/grades/4/theme/6', icon: 'theme' },
    { name: 'grade theme 7', route: '/grades/4/theme/7', icon: 'theme' },
    { name: 'grade theme 8', route: '/grades/4/theme/8', icon: 'theme' },
    { name: 'grade theme 9', route: '/grades/4/theme/9', icon: 'theme' },
    { name: 'grade theme 10', route: '/grades/4/theme/10', icon: 'theme' },
    { name: 'grade theme 11', route: '/grades/4/theme/11', icon: 'theme' },
    { name: 'grade theme 12', route: '/grades/4/theme/12', icon: 'theme' },
    { name: 'grade theme 13', route: '/grades/4/theme/13', icon: 'theme' },
    { name: 'grade theme 14', route: '/grades/4/theme/14', icon: 'theme' },
    { name: 'grade theme 15', route: '/grades/4/theme/15', icon: 'theme' },
    { name: 'grade theme 16', route: '/grades/4/theme/16', icon: 'theme' },
    { name: 'grade theme 17', route: '/grades/4/theme/17', icon: 'theme' },
  ],
  [
    { name: 'grade theme 1', route: '/grades/5/theme/1', icon: 'theme' },
    { name: 'grade theme 2', route: '/grades/5/theme/2', icon: 'theme' },
    { name: 'grade theme 3', route: '/grades/5/theme/3', icon: 'theme' },
    { name: 'grade theme 4', route: '/grades/5/theme/4', icon: 'theme' },
    { name: 'grade theme 5', route: '/grades/5/theme/5', icon: 'theme' },
    { name: 'grade theme 6', route: '/grades/5/theme/6', icon: 'theme' },
    { name: 'grade theme 7', route: '/grades/5/theme/7', icon: 'theme' },
    { name: 'grade theme 8', route: '/grades/5/theme/8', icon: 'theme' },
    { name: 'grade theme 9', route: '/grades/5/theme/9', icon: 'theme' },
    { name: 'grade theme 10', route: '/grades/5/theme/10', icon: 'theme' },
    { name: 'grade theme 11', route: '/grades/5/theme/11', icon: 'theme' },
    { name: 'grade theme 12', route: '/grades/5/theme/12', icon: 'theme' },
    { name: 'grade theme 13', route: '/grades/5/theme/13', icon: 'theme' },
    { name: 'grade theme 14', route: '/grades/5/theme/14', icon: 'theme' },
    { name: 'grade theme 15', route: '/grades/5/theme/15', icon: 'theme' },
    { name: 'grade theme 16', route: '/grades/5/theme/16', icon: 'theme' },
    { name: 'grade theme 17', route: '/grades/5/theme/17', icon: 'theme' },
    { name: 'grade theme 18', route: '/grades/5/theme/18', icon: 'theme' },
  ],
  [
    { name: 'grade theme 1', route: '/grades/6/theme/1', icon: 'theme' },
    { name: 'grade theme 2', route: '/grades/6/theme/2', icon: 'theme' },
    { name: 'grade theme 3', route: '/grades/6/theme/3', icon: 'theme' },
    { name: 'grade theme 4', route: '/grades/6/theme/4', icon: 'theme' },
    { name: 'grade theme 5', route: '/grades/6/theme/5', icon: 'theme' },
    { name: 'grade theme 6', route: '/grades/6/theme/6', icon: 'theme' },
    { name: 'grade theme 7', route: '/grades/6/theme/7', icon: 'theme' },
    { name: 'grade theme 8', route: '/grades/6/theme/8', icon: 'theme' },
    { name: 'grade theme 9', route: '/grades/6/theme/9', icon: 'theme' },
    { name: 'grade theme 10', route: '/grades/6/theme/10', icon: 'theme' },
    { name: 'grade theme 11', route: '/grades/6/theme/11', icon: 'theme' },
    { name: 'grade theme 12', route: '/grades/6/theme/12', icon: 'theme' },
    { name: 'grade theme 13', route: '/grades/6/theme/13', icon: 'theme' },
    { name: 'grade theme 14', route: '/grades/6/theme/14', icon: 'theme' },
    { name: 'grade theme 15', route: '/grades/6/theme/15', icon: 'theme' },
    { name: 'grade theme 16', route: '/grades/6/theme/16', icon: 'theme' },
    { name: 'grade theme 17', route: '/grades/6/theme/17', icon: 'theme' },
  ],
  [
    { name: 'grade theme 1', route: '/grades/7/theme/1', icon: 'theme' },
    { name: 'grade theme 2', route: '/grades/7/theme/2', icon: 'theme' },
    { name: 'grade theme 3', route: '/grades/7/theme/3', icon: 'theme' },
    { name: 'grade theme 4', route: '/grades/7/theme/4', icon: 'theme' },
    { name: 'grade theme 5', route: '/grades/7/theme/5', icon: 'theme' },
    { name: 'grade theme 6', route: '/grades/7/theme/6', icon: 'theme' },
    { name: 'grade theme 7', route: '/grades/7/theme/7', icon: 'theme' },
    { name: 'grade theme 8', route: '/grades/7/theme/8', icon: 'theme' },
    { name: 'grade theme 9', route: '/grades/7/theme/9', icon: 'theme' },
    { name: 'grade theme 10', route: '/grades/7/theme/10', icon: 'theme' },
    { name: 'grade theme 11', route: '/grades/7/theme/11', icon: 'theme' },
    { name: 'grade theme 12', route: '/grades/7/theme/12', icon: 'theme' },
    { name: 'grade theme 13', route: '/grades/7/theme/13', icon: 'theme' },
    { name: 'grade theme 14', route: '/grades/7/theme/14', icon: 'theme' },
    { name: 'grade theme 15', route: '/grades/7/theme/15', icon: 'theme' },
    { name: 'grade theme 16', route: '/grades/7/theme/16', icon: 'theme' },
    { name: 'grade theme 17', route: '/grades/7/theme/17', icon: 'theme' },
    { name: 'grade theme 18', route: '/grades/7/theme/18', icon: 'theme' },
  ],
  [
    { name: 'grade theme 1', route: '/grades/8/theme/1', icon: 'theme' },
    { name: 'grade theme 2', route: '/grades/8/theme/2', icon: 'theme' },
    { name: 'grade theme 3', route: '/grades/8/theme/3', icon: 'theme' },
    { name: 'grade theme 4', route: '/grades/8/theme/4', icon: 'theme' },
    { name: 'grade theme 5', route: '/grades/8/theme/5', icon: 'theme' },
    { name: 'grade theme 6', route: '/grades/8/theme/6', icon: 'theme' },
    { name: 'grade theme 7', route: '/grades/8/theme/7', icon: 'theme' },
    { name: 'grade theme 8', route: '/grades/8/theme/8', icon: 'theme' },
    { name: 'grade theme 9', route: '/grades/8/theme/9', icon: 'theme' },
    { name: 'grade theme 10', route: '/grades/8/theme/10', icon: 'theme' },
    { name: 'grade theme 11', route: '/grades/8/theme/11', icon: 'theme' },
    { name: 'grade theme 12', route: '/grades/8/theme/12', icon: 'theme' },
    { name: 'grade theme 13', route: '/grades/8/theme/13', icon: 'theme' },
    { name: 'grade theme 14', route: '/grades/8/theme/14', icon: 'theme' },
    { name: 'grade theme 15', route: '/grades/8/theme/15', icon: 'theme' },
    { name: 'grade theme 16', route: '/grades/8/theme/16', icon: 'theme' },
    { name: 'grade theme 17', route: '/grades/8/theme/17', icon: 'theme' },
    { name: 'grade theme 18', route: '/grades/8/theme/18', icon: 'theme' },
  ],
  [
    { name: 'grade theme 1', route: '/grades/9/theme/1', icon: 'theme' },
    { name: 'grade theme 2', route: '/grades/9/theme/2', icon: 'theme' },
    { name: 'grade theme 3', route: '/grades/9/theme/3', icon: 'theme' },
    { name: 'grade theme 4', route: '/grades/9/theme/4', icon: 'theme' },
    { name: 'grade theme 5', route: '/grades/9/theme/5', icon: 'theme' },
    { name: 'grade theme 6', route: '/grades/9/theme/6', icon: 'theme' },
    { name: 'grade theme 7', route: '/grades/9/theme/7', icon: 'theme' },
    { name: 'grade theme 8', route: '/grades/9/theme/8', icon: 'theme' },
    { name: 'grade theme 9', route: '/grades/9/theme/9', icon: 'theme' },
    { name: 'grade theme 10', route: '/grades/9/theme/10', icon: 'theme' },
    { name: 'grade theme 11', route: '/grades/9/theme/11', icon: 'theme' },
    { name: 'grade theme 12', route: '/grades/9/theme/12', icon: 'theme' },
    { name: 'grade theme 13', route: '/grades/9/theme/13', icon: 'theme' },
    { name: 'grade theme 14', route: '/grades/9/theme/14', icon: 'theme' },
    { name: 'grade theme 15', route: '/grades/9/theme/15', icon: 'theme' },
    { name: 'grade theme 16', route: '/grades/9/theme/16', icon: 'theme' },
    { name: 'grade theme 17', route: '/grades/9/theme/17', icon: 'theme' },
    { name: 'grade theme 18', route: '/grades/9/theme/18', icon: 'theme' },
  ],
  [
    {
      name: 'baccalaureate theme 1',
      route: '/baccalaureate/1/theme/1',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 2',
      route: '/baccalaureate/1/theme/2',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 3',
      route: '/baccalaureate/1/theme/3',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 4',
      route: '/baccalaureate/1/theme/4',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 5',
      route: '/baccalaureate/1/theme/5',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 6',
      route: '/baccalaureate/1/theme/6',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 7',
      route: '/baccalaureate/1/theme/7',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 8',
      route: '/baccalaureate/1/theme/8',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 9',
      route: '/baccalaureate/1/theme/9',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 10',
      route: '/baccalaureate/1/theme/10',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 11',
      route: '/baccalaureate/1/theme/11',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 12',
      route: '/baccalaureate/1/theme/12',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 13',
      route: '/baccalaureate/1/theme/13',
      icon: 'theme',
    },
  ],
  [
    {
      name: 'baccalaureate theme 1',
      route: '/baccalaureate/2/theme/1',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 2',
      route: '/baccalaureate/2/theme/2',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 3',
      route: '/baccalaureate/2/theme/3',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 4',
      route: '/baccalaureate/2/theme/4',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 5',
      route: '/baccalaureate/2/theme/5',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 6',
      route: '/baccalaureate/2/theme/6',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 7',
      route: '/baccalaureate/2/theme/7',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 8',
      route: '/baccalaureate/2/theme/8',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 9',
      route: '/baccalaureate/2/theme/9',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 10',
      route: '/baccalaureate/2/theme/10',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 11',
      route: '/baccalaureate/2/theme/11',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 12',
      route: '/baccalaureate/2/theme/12',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 13',
      route: '/baccalaureate/2/theme/13',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 14',
      route: '/baccalaureate/2/theme/14',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 15',
      route: '/baccalaureate/2/theme/15',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 16',
      route: '/baccalaureate/2/theme/16',
      icon: 'theme',
    },
    {
      name: 'baccalaureate theme 17',
      route: '/baccalaureate/2/theme/17',
      icon: 'theme',
    },
  ],
];

const routesReducer = (state = routes, action) => {
  return state;
};

export default routesReducer;
